### PR TITLE
Fixed Alexa handlers.py-Cognitive Complexity in async_api_set_mode function

### PR DESCRIPTION
**Pull request by pamali-gu**
Sonarqube code smell - Refactor this function to reduce its Cognitive Complexity from 33 to the 15 allowed.
Cognitive Complexity of functions should not be too high

Changes:
Break down the logic into smaller functions.
Tested:
Ran Sonarqube after the change. The issue was no longer present.

Note - There is no test file available for Alexa Handlers

### CODE REVIEW

**Review by ChrisAxt — APPROVED** [review]
Good job!

**Review by AndreaBForce — APPROVED** [review]
lgtm

**Review by tavantzish — APPROVED** [review]
Good logic extraction!

**Review by Sara-Maha — APPROVED** [review]
Nice!

**Review by Marble879 — APPROVED** [review]
Looks great!

**Pull request merged**
