### PR TITLE
Fixed Cognitive complexity issue #2 in websocket_api.py

### PR DESCRIPTION
**Pull request by Sara-Maha**
Changes:
- Break down the logic into smaller functions.
- Reduce nested conditions

Tested:
Ran Sonarqube once the changes had been made - The issue was no longer present.
Ran the particular test file related to this module - All tests passed, as seen below.

image

### CODE REVIEW

**Review by tavantzish — APPROVED** [review]
Nicely done!

**Review by ChrisAxt — APPROVED** [review]
Nice!

**Review by AndreaBForce — APPROVED** [review]
good fixes

**Review by Marble879 — APPROVED** [review]
looks great!!

**Review by pamali-gu — APPROVED** [review]
Nice

**Review by tavantzish — APPROVED** [review]
Good job!

**Pull request merged**
