### PR TITLE
Reduce complexity (33 to 15)- async_api_set_range

### PR DESCRIPTION
**Pull request by pamali-gu**
Sonarqube code smell - Refactor this function to reduce its Cognitive Complexity from 33 to the 15 allowed.
Cognitive Complexity of functions should not be too high (async_api_set_range in Alexa Handlers)

Changes:
Break down the logic into smaller functions.
Handle duplicate codes
Tested:
Ran Sonarqube after the change. The issue was no longer present.

Note - There is no test file available for Alexa Handlers

### CODE REVIEW

**Review by Marble879 — APPROVED** [review]
LGTM!!

**Review by Sara-Maha — APPROVED** [review]
Nice fix!

**Review by tavantzish — APPROVED** [review]
Nice fix!

**Review by ChrisAxt — APPROVED** [review]
Nice fix!

**Review by AndreaBForce — APPROVED** [review]
lgtm

**Pull request merged**
