### PR TITLE
Fixed Alexa handlers.py - duplicating of a literal "Alexa.SecurityPanelController"

### PR DESCRIPTION
**Pull request by pamali-gu**
Sonarqube code smell - Define a constant instead of duplicating this literal "Alexa.SecurityPanelController" 3 times.

Changes:
Defined a constant for the value "Alexa.SecurityPanelController" and replaced the values in the file.
Tested:
Ran Sonarqube after the change. The issue was no longer present.

Note - There is no test file available for Alexa Handlers

### CODE REVIEW

**Review by ChrisAxt — APPROVED** [review]

**Review by tavantzish — APPROVED** [review]
Nice work!

**Review by Sara-Maha — APPROVED** [review]

**Review by AndreaBForce — APPROVED** [review]
Intresting fix

**Review by Marble879 — APPROVED** [review]
Looks great!

**Comment by pamali-gu** [comment]
Ran tests for the whole component

Screenshot 2024-10-17 at 07 59 44

**Pull request merged**
