### PR TITLE
Fixed the High Cognitive Complexity of the method “async_enable_proactive_mode” in the Alexa/state_report.py

### PR DESCRIPTION
**Pull request by tavantzish**
Changes:
* Break down the logic into smaller functions.
* Combine the logic of some if statements to reduce the nested conditions.

Tested:
* Ran Sonarqube once the changes had been made - The issue was no longer present.
* Ran the particular test file that related to this module - All tests passed, as seen below.

Screenshot 2024-10-12 at 17 56 38

### CODE REVIEW

**Review by ChrisAxt — APPROVED** [review]
Nice work!

**Review by Sara-Maha — APPROVED** [review]
Nice fix!

**Review by Marble879 — APPROVED** [review]
Looks great!

**Review by AndreaBForce — APPROVED** [review]
big fix

**Pull request merged**
