### PR TITLE
Suggestion list

### PR DESCRIPTION
**Pull request by ChrisAxt**
## Helper functions for suggestion feature 

- Function to return a list of sensors based on given the category
- (Internal helper) Function to average sensor readings over a given period
- (Internal helper) Function to get the range of the sensor
- (Internal helper)  Function to check if a given value is a number

##
- Tests written for all functions above as well as mock objects.

### CODE REVIEW

**Review by tavantzish — APPROVED** [review]
Nice work!

**Review by Marble879 — APPROVED** [review]
Great work!

**Review by Sara-Maha — APPROVED** [review]
great work!

**Review by pamali-gu — APPROVED** [review]
Nicely done

**Pull request merged**
