### PR TITLE
Fix Cognitive complexity issue #2 in capabilities.py: get_property()

### PR DESCRIPTION
**Pull request by Sara-Maha**
Changes:
- Break down the logic into smaller functions.

Tested:
- Ran Sonarqube once the changes had been made - The issue was no longer present.
- Ran the particular test file related to this module - All tests passed, as seen below.

image

### CODE REVIEW

**Review by Marble879 — APPROVED** [review]
Looks great!

**Review by AndreaBForce — APPROVED** [review]
nice change

**Review by tavantzish — APPROVED** [review]
LGTM!

**Review by pamali-gu — APPROVED** [review]
Nicely done

**Pull request merged**
