### PR TITLE
Reduce Cognitive Complexity from 47-async_api_adjust_range.

### PR DESCRIPTION
**Pull request by pamali-gu**
Sonarqube code smell - Refactor this function to reduce its Cognitive Complexity from 33 to the 15 allowed.
Cognitive Complexity of functions should not be too high (async_api_adjust_range in Alexa Handlers)

Changes:
Break down the logic into smaller functions.
Handle duplicate codes
Tested:
Ran Sonarqube after the change. The issue was no longer present.

Note - There is no test file available for Alexa Handlers

### CODE REVIEW

**Review by Marble879 — APPROVED** [review]
Looks great!

**Review by Sara-Maha — APPROVED** [review]
Good job!

**Review by tavantzish — APPROVED** [review]
LGTM!

**Review by ChrisAxt — APPROVED** [review]
Nice!

**Review by AndreaBForce — APPROVED** [review]
lgtm

**Pull request merged**
