### PR TITLE
Refactor again due to testing failures

### PR DESCRIPTION
**Pull request by tavantzish**
**Changes**:
- Refactor auth/init.py again to pass the failing tests
- Refactor assist_pipeline/pipeline.py to reduce the Cognitive Complexity by 1.

**Tested:**
- Ran SonarQube, no issues anymore!
- Ran the auth/test_init.py file and all test cases passed.

### CODE REVIEW

**Review by Sara-Maha — APPROVED** [review]
Nice!

**Review by Marble879 — APPROVED** [review]
Looks great!

**Review by ChrisAxt — APPROVED** [review]
Nice fix!

**Review by pamali-gu — APPROVED** [review]
Nice work

**Pull request merged**
