### PR TITLE
Fix complexity error in buienradar sensor file

### PR DESCRIPTION
**Pull request by ChrisAxt**
### Changes:
Created a separate functions to handle the processing of sensor type and weather symbol and status text.
Call the created function from the process function.
### Tested:
Ran Sonarqube after the change was made: The congitive complexity issue was resolved.
Ran the test_sensor.py test file which passes after the changes were made.

Capture

### CODE REVIEW

**Review by AndreaBForce — APPROVED** [review]
lgtm

**Review by Sara-Maha — APPROVED** [review]
Good job!

**Review by tavantzish — APPROVED** [review]
Nice job guys!

**Review by pamali-gu — APPROVED** [review]
Good work

**Pull request merged**
