### PR TITLE
Fixed the high cognitive complexity of the methods (_async_resolve_default_pipeline_settings, wake_word_detection) and the variable type of the language variable in the class PipelineRun

### PR DESCRIPTION
**Pull request by tavantzish**
Changes:
* Break down the logic into smaller functions.
* Change the variable initialisation in the Class Pipeline. 

Tested:
* Ran Sonarqube once the changes had been made - The issue was no longer present.
* Ran the particular test file that related to this module - All tests passed, as seen below.

Screenshot 2024-10-13 at 16 00 22

### CODE REVIEW

**Review by Marble879 — APPROVED** [review]
Looks great! Nice job :rocket:

**Review by ChrisAxt — APPROVED** [review]
Nice fix!

**Review by Sara-Maha — APPROVED** [review]
Nice!

**Review by pamali-gu — APPROVED** [review]
Nice job

**Pull request merged**
