### PR TITLE
Fix 'Cognitive Complexity of functions should not be too high' of the vad.py process function

### PR DESCRIPTION
**Pull request by Marble879**
#### Changes: 
- Created a separate function to handle the 'not in command' situation of the process function.
- Call the created function from the process function.

#### Tested:
- Ran Sonarqube after the change was made: The congitive complexity issue was resolved. 
- Ran the vad.py test file which passes after the changes were made.

image

### CODE REVIEW

**Review by ChrisAxt — APPROVED** [review]
Nice! Good solution to reduce the complexity!

**Review by Sara-Maha — APPROVED** [review]
Nice!

**Review by AndreaBForce — APPROVED** [review]
Good fix

**Review by tavantzish — APPROVED** [review]
Looks good!

**Review by pamali-gu — APPROVED** [review]
Nice

**Pull request merged**
