### PR TITLE
Buienradar/sensor

### PR DESCRIPTION
**Pull request by ChrisAxt**
### Changes:
Created a constant for string values "mdi:weather-partly-cloudy" and "No forecast for fcday="
Fixed some type errors from a previous commits
### Tested:
Ran Sonarqube after the change was made: The cognitive complexity issue was resolved. All issues in the sensor file are now resolved. 
Ran the test_sensor.py test file which passes after the changes were made.

Capture

### CODE REVIEW

**Review by tavantzish — APPROVED** [review]
LGTM!

**Review by Sara-Maha — APPROVED** [review]

**Review by Marble879 — APPROVED** [review]
Looks great! Nice bug fixes :rocket:

**Review by AndreaBForce — APPROVED** [review]
approved

**Review by pamali-gu — APPROVED** [review]
Nice fixes

**Pull request merged**
