### PR TITLE
Fixed duplicating literal "@type" 5 times in resources in alexa and a…

### PR DESCRIPTION
**Pull request by Sara-Maha**
Changes:
Define a constant for the value and replace the values in the file.

Tested:
Added the test file since it was not there and ran the test before the change. 
Ran the test again after the change. 
Ran Sonarqube after the change - The issue was no longer present.

image

### CODE REVIEW

**Comment by Sara-Maha** [comment]
By the way, the quality gate failed for this in SonarQube due to 'Uncovered Lines on New Code'

**Comment by Marble879** [comment]
Looks really great! Nice work with the new test file :rocket:

**Review by Marble879 — APPROVED** [review]
Looks great! Nice work with the new test file :rocket:

**Review by tavantzish — APPROVED** [review]
Good job, adding the new test case!

**Review by pamali-gu — APPROVED** [review]
Nice job !!

**Comment by ChrisAxt** [comment]
> By the way, the quality gate failed for this in SonarQube due to 'Uncovered Lines on New Code'

I get the same issue with mine but I think as long as the initial issue is gone, and no new ones come up i think it's fine.

**Review by ChrisAxt — APPROVED** [review]

**Review by AndreaBForce — APPROVED** [review]
good

**Pull request merged**
