### PR TITLE
Fixed Cognitive complexity issue #1 in websocket_api.py

### PR DESCRIPTION
**Pull request by Sara-Maha**
Changes:
- Break down the logic into smaller functions.
- Extract repeated logic and reduce nested conditions

Tested:
- Ran Sonarqube once the changes had been made - The issue was no longer present.
- Ran the particular test file related to this module - All tests passed, as seen below.

image

### CODE REVIEW

**Review by ChrisAxt — APPROVED** [review]
Nice!

**Review by AndreaBForce — APPROVED** [review]
Nice resolve

**Review by tavantzish — APPROVED** [review]
Nice job!

**Review by Marble879 — APPROVED** [review]
LGTM!

**Review by pamali-gu — APPROVED** [review]
Well done

**Pull request merged**
