### PR TITLE
Fix/auth store fix, reduced cyclomatic complexity and fixed value

### PR DESCRIPTION
**Pull request by AndreaBForce**
Changes:

Reduced cyclomatic complexity from method async_load
Fixed Values assigned to variables should match their type annotiations
Tested:
Ran Sonarqube once the changes had been made - The issue was no longer present.
Ran the particular test file related to this module - All tests passed, as seen below.
image

### CODE REVIEW

**Review by Marble879 — APPROVED** [review]
Looks great! :rocket:

**Review by tavantzish — APPROVED** [review]
Nice fix!

**Review by ChrisAxt — APPROVED** [review]

**Review by pamali-gu — APPROVED** [review]
Nice

**Review by Sara-Maha — APPROVED** [review]
Nice fix!

**Pull request merged**
