### PR TITLE
Plant placement suggestion

### PR DESCRIPTION
**Pull request by pamali-gu**
Added plant placement suggestion feature

- Added UI in the lightmap panel to provide the chat popup
- Added a webhook to send plant name to backend
- Connected the Gemini API in the backend and get light density results
- Check range with the existing sensors and provide sensor results in the frontend

Co-authored: @Sara-Maha

### CODE REVIEW

**Review by ChrisAxt — CHANGES_REQUESTED** [review]
Just did some testing, and it seems the response it wrong, this plant has a low light requirement and I should get the suggestion of light_sensor_2. Maybe it's also a good idea to return the category so in the case of no sensors available, the user still gets an idea of the light requirements?

Screenshot from 2024-12-12 10-07-55

**Comment by Sara-Maha** [comment]
@ChrisAxt according to the calculations there is no sensor for the low category. Do you know what values we should put to get one sensor for low category? We tried changing max and min values but still couldn't find the way
Sensor 2 is taken under medium category. The rest is taken under high category.

**Comment by pamali-gu** [comment]
Added the suggestion by @ChrisAxt to show the light density values in the frontend chat.

Screenshot 2024-12-12 at 12 15 10

**Review by AndreaBForce — APPROVED** [review]
LGTM! APPROVED

**Review by tavantzish — APPROVED** [review]
Nice work! Good improvement!

**Review by ChrisAxt — APPROVED** [review]

**Comment by ChrisAxt** [comment]
Good job, really nice feature!

**Pull request merged**
