### PR TITLE
Fixed Cognitive complexity issue #5 in capabilities.py: capability_resources()

### PR DESCRIPTION
**Pull request by Sara-Maha**
Changes:
- Break down the logic into smaller functions.
- Extract repeated logic and reduce nested conditions

Tested:
- Ran Sonarqube once the changes had been made - The issue was no longer present.
- Ran the particular test file related to this module - All tests passed (66)

### CODE REVIEW

**Review by ChrisAxt — APPROVED** [review]

**Review by tavantzish — APPROVED** [review]
LGTM!

**Review by Marble879 — APPROVED** [review]
Looks good!

**Review by pamali-gu — APPROVED** [review]
Nice work

**Review by AndreaBForce — APPROVED** [review]
Good breakdown

**Pull request merged**
