### PR TITLE
Fixed Cognitive complexity issue #3 in capabilities.py: get_property()

### PR DESCRIPTION
**Pull request by Sara-Maha**
Changes:
Break down the logic into smaller functions.

Tested:
Ran Sonarqube once the changes had been made - The issue was no longer present.
Ran the particular test file related to this module - All tests passed, as seen below.

image

### CODE REVIEW

**Review by Marble879 — APPROVED** [review]
Looks great!

**Review by AndreaBForce — APPROVED** [review]
good breakdown

**Review by tavantzish — APPROVED** [review]
Nice logic extraction!

**Review by pamali-gu — APPROVED** [review]
Nice

**Pull request merged**
