### PR TITLE
Fixed the Increased Cognitive Complexity issue in auth/__init__.py file

### PR DESCRIPTION
**Pull request by tavantzish**
Changes:
* Extract the logic of the multiple if statements to smaller functions. So, each function performs a particular task.

Tested:
* Ran Sonarqube once the changes had been made - The issue was no longer present.
* Ran the particular test file that related to this module - All tests passed, as seen below.

test_auth:test_init

### CODE REVIEW

**Review by AndreaBForce — APPROVED** [review]
good extract

**Review by Sara-Maha — APPROVED** [review]
Nice fix!

**Review by ChrisAxt — APPROVED** [review]
Nice work!

**Review by Marble879 — APPROVED** [review]
Looks great!

**Review by pamali-gu — APPROVED** [review]
Nicely done

**Pull request merged**
